### ISSUE TITLE
Config changes?

### ISSUE THREAD

**Issue by vorkos** [alexellis/quickstart-prometheus#1]
https://github.com/alexellis/quickstart-prometheus/blob/29e76162d0f3ef7b85d84c43c6d433590754aefa/docker-compose.yml#L7
for me "--config.file=/etc/prometheus/prometheus.yml  --storage.tsdb.path=/prometheus" works better

**Comment by alexellis** [comment]
Yes this is because I used the latest tag and Prometheus made breaking changes. Would you like to pr this?

**Comment by alexellis** [comment]
Fixed in f2e0358c0cc9811d1ed305ea352d43d047bb7edf - thanks for reporting.

**Comment by krisanovdev** [comment]
We can close it I guess?
